eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
