server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: Comment-Service
          uri: lb://Comment-Service
          predicates:
            - Path=/api/comment-service/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification-service/**

  security:
    oauth2:
      resourceserver:
        jwk:
          jwk-set-uri: http://localhost:8080
          issuer-uri: https://dev-qx1buviid5yofprn.us.auth0.com/

allowed-origin: "http://localhost:4200"
