eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidcomment
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: UTC
