server:
  port: 8060

auth0:
  audience: http://localhost:8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-qx1buviid5yofprn.us.auth0.com/
          jwk-set-uri: http://localhost:8080
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidcomment
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: UTC

auth:
  properties:
    domain: https://dev-qx1buviid5yofprn.us.auth0.com
    client-Id: 35wCRcng89sdB5p2THHFTl9lF0mOThsL
    client-secret: 8orKJtn9v2WWbxt2hUo4HS4Yelb1C2kRHXbCKqTI1N8PCoPUooUpYcuZ-ayBXDJu

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

allowed-origin: 'http://localhost:4200'