server:
  port: 8443

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rapidcomment
    username: postgres
    password: password
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update

    rabbitmq:
      host: "127.0.0.1"
      port: "5672"
      username: "guest"
      password: "guest"


mail-trap:
  from: "mailtrap@chiragpadyal.me"
  api-key: ""
  api-key: ""
  cron: "0 */5 * ? * *"
  username: "api"
  port: 587
  host: "live.smtp.mailtrap.io"

email-server-url: "http://localhost:8443/notify/push-mail"
