server:
  port: 8443

mail-trap:
  from: "mailtrap@chiragpadyal.me"
  api-key: "b7c79b966f0ff19f845473c0ede02997"
  cron: "0 */5 * ? * *"
  username: "api"
  port: 587
  host: "live.smtp.mailtrap.io"

allowed-origin: "http://localhost:4200"
