server:
  port: 8443

eureka:
  client:
    service-url:
      default-zone: http://service-discovery:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://database:5432/rapidcomment
    username: postgres
    password: password
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update

    rabbitmq:
      host: rabbitmq
      port: "5672"
      username: "guest"
      password: "guest"

mail-trap:
  from: "mailtrap@chiragpadyal.me"
  api-key: "b7c79b966f0ff19f845473c0ede02997"
  cron: "0 */5 * ? * *"
  username: "api"
  port: 587
  host: "live.smtp.mailtrap.io"

email-server-url: "http://service-discovery:8080/api/notification-service/push-mail"

allowed-origin: "http://localhost:4200"
