eureka:
  client:
    service-url:
      default-zone: http://service-discovery:8761/eureka/

email-server-url: "http://service-discovery:8080/api/notification-service/push-mail"

spring:
  datasource:
    url: jdbc:postgresql://database:5432/rapidcomment
    username: postgres
    password: password
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update

    rabbitmq:
      host: rabbitmq
      port: "5672"
      username: "guest"
      password: "guest"
